name: 'retail_dsy'
version: '1.0.0'
config-version: 2

profile: 'retail_dsy'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  retail_dsy:
    staging:
      +materialized: view
    transform:
      +materialized: table