version: 2

sources:
  - name: retail_dsy
    database: ext3rncrm
    schema: retail_dsy
    tables:
      - name: raw_invoice
        columns:
          - name: InvoiceNo
            tests:
              - not_null
      - name: raw_country
        columns:
          - name: CountryCode
            tests:
              - not_null