version: 2

models:
  - name: fct_invoices
    description: |
      **Table de faits centrale du projet retail ETL.**
      
      Contient les données transactionnelles des ventes avec les clés étrangères 
      vers les dimensions. Cette table est optimisée pour les analyses de vente, 
      le reporting financier et les métriques de performance.
      
      **Granularité** : Une ligne par item de facture
      **Source** : raw_invoice (après transformation et jointures)
      **Fréquence** : Mise à jour quotidienne
      **Volume estimé** : ~500K lignes/mois
    columns:
      - name: invoice_id
        description: "Identifiant de la facture"
        tests:
          - not_null
      
      - name: datetime_id
        description: "Clé étrangère vers la dimension datetime"
        tests:
          - not_null
          - relationships:
              to: ref('dim_datetime')
              field: datetime_id
      
      - name: product_id
        description: "Clé étrangère vers la dimension produit"
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_id
      
      - name: customer_id
        description: "Clé étrangère vers la dimension client"
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_id
      
      - name: quantity
        description: "Quantité vendue"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: false
      
      - name: total
        description: "Montant total de la ligne de facture"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: false

  - name: dim_customer
    description: |
      **Dimension des clients** contenant les informations uniques par client et pays.
      
      Cette table de dimension regroupe les clients par combinaison unique de 
      CustomerID et Country, permettant l'analyse géographique des ventes.
      La jointure avec raw_country enrichit les données avec les codes ISO.
      
      **Granularité** : Un enregistrement par combinaison CustomerID + Country
      **Clé primaire** : customer_id (surrogate key générée)
      **Sources** : raw_invoice, raw_country
      **Type SCD** : SCD Type 1 (écrasement)
    columns:
      - name: customer_id
        description: "Clé primaire de la dimension client"
        tests:
          - unique
          - not_null
      
      - name: country
        description: "Pays du client"
        tests:
          - not_null
      
      - name: iso
        description: "Code ISO du pays"
        tests:
          - accepted_values:
              values: ['AD', 'AE', 'AF', 'AG', 'AI', 'AL', 'AM', 'AO', 'AQ', 'AR', 'AS', 'AT', 'AU', 'AW', 'AX', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BL', 'BM', 'BN', 'BO', 'BQ', 'BR', 'BS', 'BT', 'BV', 'BW', 'BY', 'BZ', 'CA', 'CC', 'CD', 'CF', 'CG', 'CH', 'CI', 'CK', 'CL', 'CM', 'CN', 'CO', 'CR', 'CU', 'CV', 'CW', 'CX', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'EH', 'ER', 'ES', 'ET', 'FI', 'FJ', 'FK', 'FM', 'FO', 'FR', 'GA', 'GB', 'GD', 'GE', 'GF', 'GG', 'GH', 'GI', 'GL', 'GM', 'GN', 'GP', 'GQ', 'GR', 'GS', 'GT', 'GU', 'GW', 'GY', 'HK', 'HM', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IM', 'IN', 'IO', 'IQ', 'IR', 'IS', 'IT', 'JE', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KP', 'KR', 'KW', 'KY', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'LY', 'MA', 'MC', 'MD', 'ME', 'MF', 'MG', 'MH', 'MK', 'ML', 'MM', 'MN', 'MO', 'MP', 'MQ', 'MR', 'MS', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NC', 'NE', 'NF', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NU', 'NZ', 'OM', 'PA', 'PE', 'PF', 'PG', 'PH', 'PK', 'PL', 'PM', 'PN', 'PR', 'PS', 'PT', 'PW', 'PY', 'QA', 'RE', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SD', 'SE', 'SG', 'SH', 'SI', 'SJ', 'SK', 'SL', 'SM', 'SN', 'SO', 'SR', 'SS', 'ST', 'SV', 'SX', 'SY', 'SZ', 'TC', 'TD', 'TF', 'TG', 'TH', 'TJ', 'TK', 'TL', 'TM', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'UM', 'US', 'UY', 'UZ', 'VA', 'VC', 'VE', 'VG', 'VI', 'VN', 'VU', 'WF', 'WS', 'YE', 'YT', 'ZA', 'ZM', 'ZW']
              quote: false

  - name: dim_product
    description: |
      **Dimension des produits** avec gestion des variations de prix.
      
      Contrairement à une dimension produit classique, cette table capture 
      les variations de prix en créant un enregistrement unique par combinaison 
      StockCode + Description + UnitPrice. Cela permet de tracker l'historique 
      des prix et les promotions.
      
      **Granularité** : Un enregistrement par StockCode + Description + Prix
      **Clé primaire** : product_id (surrogate key générée)
      **Source** : raw_invoice (distinct values)
      **Particularité** : Gère les variations de prix dans le temps
    columns:
      - name: product_id
        description: "Clé primaire de la dimension produit"
        tests:
          - unique
          - not_null
      
      - name: stock_code
        description: "Code stock du produit"
        tests:
          - not_null
      
      - name: description
        description: "Description du produit"
        tests:
          - not_null
      
      - name: price
        description: "Prix unitaire du produit"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: false

  - name: dim_datetime
    description: |
      **Dimension temporelle** avec parsing intelligent des formats de date.
      
      Cette table transforme les chaînes de date variables du système source 
      en structure temporelle normalisée. Gère deux formats principaux :
      - "DD/MM/YYYY HH:MM" (16 caractères)
      - "MM/DD/YY HH:MM" (≤14 caractères)
      
      **Granularité** : Un enregistrement par datetime unique
      **Clé primaire** : datetime_id (datetime original en string)
      **Source** : raw_invoice.InvoiceDate
      **Utilisation** : Analyses temporelles, reporting périodique
    columns:
      - name: datetime_id
        description: "Clé primaire de la dimension datetime"
        tests:
          - unique
          - not_null
      
      - name: datetime
        description: "Date et heure parsées"
        tests:
          - not_null
      
      - name: year
        description: "Année"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 2000
              max_value: 2030
      
      - name: month
        description: "Mois"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 12
      
      - name: day
        description: "Jour"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 31
      
      - name: hour
        description: "Heure"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 23
      
      - name: minute
        description: "Minute"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 59
      
      - name: weekday
        description: "Jour de la semaine"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 7