version: 2

models:
  # ============================================================================
  # TABLES DE DIMENSIONS
  # ============================================================================

  # --------------------------------------------------------------------------
  # Dimension Client
  # --------------------------------------------------------------------------
  - name: dim_customer
    description: |
      **Dimension des clients** - Informations uniques par client et pays.
      
      Granularité : Un enregistrement par combinaison CustomerID + Country
      Clé primaire : customer_id (surrogate key)
      Sources : raw_invoice, raw_country
    
    columns:
      - name: customer_id
        description: Clé primaire de la dimension client
        tests: [unique, not_null]

      - name: country
        description: Pays du client
        tests: [not_null]

      - name: iso
        description: Code ISO2 du pays


  # --------------------------------------------------------------------------
  # Dimension Produit
  # --------------------------------------------------------------------------
  - name: dim_product
    description: |
      **Dimension des produits** - Gère les variations de prix.
      
      Un produit peut avoir différents prix (product_id inclut le prix).
      Granularité : Un enregistrement par StockCode + Description + Prix
      Clé primaire : product_id (surrogate key)
    
    columns:
      - name: product_id
        description: Clé primaire de la dimension produit
        tests: [unique, not_null]

      - name: stock_code
        description: Code article du produit
        tests: [not_null]

      - name: description
        description: Description du produit

      - name: price
        description: Prix unitaire du produit (doit être > 0)


  # --------------------------------------------------------------------------
  # Dimension Temporelle
  # --------------------------------------------------------------------------
  - name: dim_datetime
    description: |
      **Dimension temporelle** - Parsing intelligent des formats de date.
      
      Gère deux formats : "DD/MM/YYYY HH:MM" et "MM/DD/YY HH:MM"
      Granularité : Un enregistrement par datetime unique
      Clé primaire : datetime_id
    
    columns:
      - name: datetime_id
        description: Clé primaire - datetime original en string

      - name: datetime
        description: Date et heure parsées

      - name: year
        description: Année extraite
        tests:
          - not_null

      - name: month
        description: Mois extrait (1-12)
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 12

      - name: day
        description: Jour du mois (1-31)

      - name: hour
        description: Heure (0-23)

      - name: minute
        description: Minute (0-59)

      - name: weekday
        description: Jour de la semaine (1=Dimanche, 7=Samedi)


  # ============================================================================
  # TABLE DE FAITS
  # ============================================================================

  # --------------------------------------------------------------------------
  # Fait Factures
  # --------------------------------------------------------------------------
  - name: fct_invoices
    description: |
      **Table de faits centrale** - Données transactionnelles des ventes.
      
      Schéma en étoile (star schema).
      Granularité : Une ligne par item de facture
      Source : raw_invoice (après transformation et jointures)
    
    # Tests au niveau table
    tests:
      - dbt_utils.expression_is_true:
          expression: "quantity > 0"

    
    columns:
      - name: invoice_id
        description: Identifiant de la facture
        tests: [not_null]

      - name: datetime_id
        description: "FK → dim_datetime"
        tests:
          - not_null
          - relationships:
              to: ref('dim_datetime')
              field: datetime_id

      - name: product_id
        description: "FK → dim_product"
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_id

      - name: customer_id
        description: "FK → dim_customer"
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_id

      - name: quantity
        description: Quantité vendue (> 0)


      - name: total
        description: Montant total (quantity  price)